id: I26A7D574
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:39:51+00:00'
last_modified: '2022-06-07T12:22:41.887897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10782
  title: བཀའ་མ་དོང་སྤྲུགས་དང་གཏེར་ཁ་གོང་འོག་གི་ཆོ་གའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    211B:
      image_group_id: I1KG10800
      title: Volume 1 of bka' ma dong sprugs dang gter kha gong 'og gi cho ga'i skor/
      total_pages: 520
      order: 1
      base_file: 211B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
