id: P000581
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:15.697216
source_metadata:
  id: bdr:W1KG10782
  title: བཀའ་མ་དོང་སྤྲུགས་དང་གཏེར་ཁ་གོང་འོག་གི་ཆོ་གའི་སྐོར།
  author: ''
  volumes:
    b4bdaa58bfc74579a9b6ae2a36b6d222:
      image_group_id: I1KG10800
      title: Volume 1 of bka' ma dong sprugs dang gter kha gong 'og gi cho ga'i skor/
      volume_number: 1
      total_pages: 520
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
